### ISSUE TITLE
Figure out how to display YAML file as table

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/CA_lib_oration#7]
It would be really helpful if we could figure out a way to have the YAML file display as a table (perhaps in a GitHub site). Maybe this is something Jekyll can do?

**Comment by chrissyrissmeyer** [comment]
From Matt: https://deepnn.github.io/mydoc_yaml_tutorial.html

**Comment by chrissyrissmeyer** [comment]
This might be helpful? https://stackoverflow.com/questions/48718373/jekyll-data-how-to-display-the-key-value-label-as-a-value-not-just-the-value

**Comment by remerjohnson** [comment]
This is possible (see screenshot), but there was a slight tweak that had to take place of the YAML properties, where instead of each first row being e.g. `"agent:contributor":` it needed an initial hyphen to replace the wrapped quotes and trailing colon, such as `- name: agent:contributor`. I think this has to do with how lists are initialized in Jekyll. 

![jekyll_yaml_table](https://user-images.githubusercontent.com/5183580/48737885-1750dd80-ec04-11e8-882c-5663fc23421d.png)

**Comment by arwenhutt** [comment]
@remerjohnson That looks promising - can you link to the branch where you are working on this so we can take a look at the live version?

**Comment by remerjohnson** [comment]
@arwenhutt Sure, I pushed the branch to this repo; the branch is named `jekyll-stuff`. 

@chrissyrissmeyer or anyone else: if you'd like to preview the site before we do a pull request, you can `git pull` for the latest version, then `git checkout jekyll-stuff` to switch to that branch, then if Ruby, Bundler, and Jekyll are installed locally for you, you can run `bundle exec jekyll serve` to preview the site. Then navigate to the model page, which will be something like `127.0.0.1:4000/model`. 

There's good documentation GitHub has developed on this process: https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/

**Comment by arwenhutt** [comment]
https://ucsdlib.github.io/CA_lib_oration/model
